services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: chat_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - app-network
        ports:
            - "8080:8080"
        depends_on:
            - postgres  # Changed from mysql to postgres

    postgres:
        image: postgres:13  # Using PostgreSQL instead of MySQL
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}  # Use the same username as before
            POSTGRES_PASSWORD: ${DB_PASSWORD}  # Use the same password as before
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network
        ports:
            - "5434:5432"  # PostgreSQL default port

    web:
        container_name: chat_web
        image: nginx:alpine
        ports:
            - "9000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    node:
        image: node:22
        container_name: websocket_node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        tty: true
        ports:
            - "5173:5173"  # For Vite development server
        environment:
            - NODE_ENV=development
        networks:
            - app-network

volumes:
    postgres_data:  # Volume for PostgreSQL data persistence

networks:
    app-network:  # Network for communication between services
        driver: bridge
